### ISSUE TITLE
How can I directly replace the original task card after changing it with Shift + D? Clicking on each save option doesn't work. You can only export a new one

### ISSUE THREAD

**Issue by symbolChai** [countd360/StudioCharaEditor#3]
Dear:
How can I directly replace the original task card after changing it with Shift + D? Clicking on each save option doesn't work. You can only export a new one

**Comment by countd360** [comment]
Overwrite the original character PNG card is not supported. Because for a studio scene there is no need to have a original character card, so when you load a scene, the character's info is included in scene file, not in chara's card. Even you load a character from local into scene, only the character's data is valid, card file info and PNG thumb data is not valid or not reliable.
Anyway, you can try to click the "Change export filename/path" button, then select the old png, it may overwrite the file. Not tested so I am not sure.
